(ns cljlox.ast)

(defrecord Binary [left operator right])
(defrecord Literal [value])
(defrecord Grouping [expression])
(defrecord Variable [name])
(defrecord Unary [operator right])
(defrecord Assign [name value])
(defrecord Expression [expression])
(defrecord If [condition then-branch else-branch])
(defrecord Print [expression])
(defrecord While [condition body])
(defrecord Block [statements])
(defrecord Var [name initializer])
