(ns cljlox.ast)

(defrecord Assign [name value])
(defrecord Binary [left operator right])
(defrecord Block [statements])
(defrecord Call [callee paren arguments])
(defrecord Expression [expression])
(defrecord Function [name params body])
(defrecord Grouping [expression])
(defrecord If [condition then-branch else-branch])
(defrecord Literal [value])
(defrecord Print [expression])
(defrecord Return [value])
(defrecord Unary [operator right])
(defrecord Var [name initializer])
(defrecord Variable [name])
(defrecord While [condition body])
